### PR TITLE
amended for Docker not installed and Not in project dir situations

### PR DESCRIPTION
**Pull request by henkvancann**

### CODE REVIEW

**Review by 2byrds — APPROVED** [review]
Thank you @henkvancann LGTM

**Comment by henkvancann** [comment]
> @henkvancann it looks like your commits aren't passing the DCO check. Probably the easiest thing to do is rebase to a single signed commit.

Ah, yes, that d.mn `-s` switch I always forget, I'll try to recover from it, but won't spend too much time on this administrative hassle. Then just forget about the proposed changes.

**Comment by henkvancann** [comment]
I can't get it going. Locally they are both signed off (see below) and when I git push --force-with-lease origin main  they won't validate by the two of them. I've tried it over and over again. ChatGPT could not help out and thinks something is wrong with the Github Actions script that's running at hyperledger-labs.

I leave it here. You could change the text yourself by hand. I  changed my .zshrc file in such a way that every commit is now globally signed off.

```
commit 163bde72747340b0c7985aa0f8c1fc3ba3a72553 (HEAD -> main, origin/main, origin/HEAD)
Author: henkvancann <hvancann@bcws.io>
Date:   Fri Feb 2 14:54:38 2024 +0000

    added link back to docker-compose command
    
    Signed-off-by: henkvancann <hvancann@bcws.io>

....
commit 3366da8204e7f0f304e5ad43522888c8699147a0
Author: henkvancann <hvancann@bcws.io>
Date:   Fri Jan 26 15:24:40 2024 +0100

    amended for Docker not installed and Not in project dir situations
    
      Signed-off-by: henkvancann <hvancann@bcws.io>
```

**Comment by 2byrds** [comment]
> I can't get it going. Locally they are both signed off (see below) and when I git push --force-with-lease origin main they won't validate by the two of them. I've tried it over and over again. ChatGPT could not help out and thinks something is wrong with the Github Actions script that's running at hyperledger-labs.
> 
> I leave it here. You could change the text yourself by hand. I changed my .zshrc file in such a way that every commit is now globally signed off.
> 
> ```
> commit 163bde72747340b0c7985aa0f8c1fc3ba3a72553 (HEAD -> main, origin/main, origin/HEAD)
> Author: henkvancann <hvancann@bcws.io>
> Date:   Fri Feb 2 14:54:38 2024 +0000
> 
>     added link back to docker-compose command
>     
>     Signed-off-by: henkvancann <hvancann@bcws.io>
> 
> ....
> commit 3366da8204e7f0f304e5ad43522888c8699147a0
> Author: henkvancann <hvancann@bcws.io>
> Date:   Fri Jan 26 15:24:40 2024 +0100
> 
>     amended for Docker not installed and Not in project dir situations
>     
>       Signed-off-by: henkvancann <hvancann@bcws.io>
> ```

Thank you for trying! looks like now it has also pulled in some of my changes from other commits. I'll make these changes manually and submit them. Thank you!

**Comment by henkvancann** [comment]
Yep, and I am good for future PRs now.

**Pull request closed without merging**
