### PR TITLE
Update to use keripy 1.1.21

### PR DESCRIPTION
**Pull request by jrayback**
Keripy 1.1.21 is currently the latest official version. The project is updated to use this version.

There are a few minor bug fixes as well.

### CODE REVIEW

**Comment by jrayback** [comment]
As far as I can tell, everything works with `keripy 1.1.21`. I probably missed some things and will happily add to the PR as needed.

**Comment by jrayback** [comment]
One note, I needed to change the label for the `weboftrust/keri` docker base image from `latest` to `latest-arm64`. This was the only way to get the 1.1.20 docker files to run on my macbook. I'm not sure what the implications for that are for developers on other platforms. There may be a larger cross-architecture strategy that needs to be worked out here.

**Review by 2byrds — APPROVED** [review]
Thank you Jonathan, LGTM

**Comment by 2byrds** [comment]
@jrayback the merge needs a conflict fix and then I'll process it

**Comment by jrayback** [comment]
@2byrds , looks like pytest is failing. It also seems some of the GitHub actions need to be updated to match the new set of dependencies. Let me fix those before you merge.

**Comment by jrayback** [comment]
@2byrds , pytest is passing now. All checks look good. You can finish evaluating the PR and merge if desirable.

**Pull request merged**
