### PR TITLE
Feat/initial keri cesr

### PR DESCRIPTION
**Pull request by 2byrds**
Draft until I can sync with Markus, etc.

### CODE REVIEW

**Comment by peacekeeper** [comment]
I had a look and I think this going in exactly the right direction!

At the moment when I try the "did webs generate" command I get an error like this, but it may be something with my local environment, or because this is still work in progress.

```
  File "/usr/local/var/did-keri-resolver/src/dkr/app/cli/commands/did/webs/generate.py", line 67, in generate
    oobiHab = self.hby.habs[aid]
KeyError: 'EPaP4GgZsB6Ww-SeSO2gwNDMNpC7-DN51X5AqiJFWkw6'
```

**Comment by 2byrds** [comment]
@peacekeeper I'm leaving this in draft to merge your work first, so i don't stomp on your work.

**Comment by 2byrds** [comment]
> I had a look and I think this going in exactly the right direction!
> 
> At the moment when I try the "did webs generate" command I get an error like this, but it may be something with my local environment, or because this is still work in progress.
> 
> ```
>   File "/usr/local/var/did-keri-resolver/src/dkr/app/cli/commands/did/webs/generate.py", line 67, in generate
>     oobiHab = self.hby.habs[aid]
> KeyError: 'EPaP4GgZsB6Ww-SeSO2gwNDMNpC7-DN51X5AqiJFWkw6'
> ```

Okay i'll take a look at this and include a fix in my next update.

**Comment by peacekeeper** [comment]
Also, I think the "requests" dependency needs to be added to setup.py, no?

https://github.com/2byrds/did-webs-resolver/blob/feat/initial_keri_cesr/src/dkr/app/cli/commands/did/webs/resolve.py#L8

**Comment by 2byrds** [comment]
> Also, I think the "requests" dependency needs to be added to setup.py, no?
> 
> https://github.com/2byrds/did-webs-resolver/blob/feat/initial_keri_cesr/src/dkr/app/cli/commands/did/webs/resolve.py#L8

good catch, i'll add it.

**Comment by 2byrds** [comment]
> I had a look and I think this going in exactly the right direction!
> 
> At the moment when I try the "did webs generate" command I get an error like this, but it may be something with my local environment, or because this is still work in progress.
> 
> ```
>   File "/usr/local/var/did-keri-resolver/src/dkr/app/cli/commands/did/webs/generate.py", line 67, in generate
>     oobiHab = self.hby.habs[aid]
> KeyError: 'EPaP4GgZsB6Ww-SeSO2gwNDMNpC7-DN51X5AqiJFWkw6'
> ```

@peacekeeper can you send me the generate command you executed. I tested this successfully (aid of demo witness):
`did-keri-resolver % dkr did webs generate --name=wan --did=did:webs:127.0.0.1:7676:BBilc4-L3tFUnfM_wJr4S4OJanAv_VmF_dJNN6vkf2Ha --oobi http://127.0.0.1:5642/oobi/BBilc4-L3tFUnfM_wJr4S4OJanAv_VmF_dJNN6vkf2Ha/controller`

**Comment by peacekeeper** [comment]
This is the command I execute in my local environment:

```
dkr did webs generate --name dkr --did did:webs:danubetech.com:EPaP4GgZsB6Ww-SeSO2gwNDMNpC7-DN51X5AqiJFWkw6 --oobi http://witnesshost:5642/oobi/EPaP4GgZsB6Ww-SeSO2gwNDMNpC7-DN51X5AqiJFWkw6/witness/BBilc4-L3tFUnfM_wJr4S4OJanAv_VmF_dJNN6vkf2Ha
```

**Comment by 2byrds** [comment]
> This is the command I execute in my local environment:
> 
> ```
> dkr did webs generate --name dkr --did did:webs:danubetech.com:EPaP4GgZsB6Ww-SeSO2gwNDMNpC7-DN51X5AqiJFWkw6 --oobi http://witnesshost:5642/oobi/EPaP4GgZsB6Ww-SeSO2gwNDMNpC7-DN51X5AqiJFWkw6/witness/BBilc4-L3tFUnfM_wJr4S4OJanAv_VmF_dJNN6vkf2Ha
> ```

Since our generate commands are using the same witness, could you try the generate command that I posted. It is a more basic test vs. yours. And will help me know if your issue is related to the witness.

**Review by peacekeeper — APPROVED** [review]
Looks good

**Pull request merged**
